### ISSUE TITLE
ForestHeaderMap.addCookie时可能会存在无法进入header的问题

### ISSUE THREAD

**Issue by yangle94** [dromara/forest#100]
如题

**Comment by mySingleLive** [comment]
请问具体是什么样的Cookie无法加入header
可以列出这样的Cookie的 domain、path、maxAge 等属性

**Comment by yangle94** [comment]
只要加入的第一个cookie在ForestCookieHeader.addCookie(cookie, strict)方法调用失败，后续cookie就会出现问题。并非特定的cookie属性有问题。

**Comment by mySingleLive** [comment]
原来合并的代码找不到了🤣
我重新改了一遍，发布到`1.5.27`版本了
