### ISSUE TITLE
Get请求不支持消息体中带Json Body，发送时消息体被忽略？

### ISSUE THREAD

**Issue by CodingOX** [dromara/forest#106]
RT。
类似的接口：
```
public interface Client {
    @Get(url = "http://127.0.0.1:8090/xxx", contentType = "application/json")
    public String saveInfo(@Body("username") MsgInfo info);
}
```
别人提供的接口，所以对接口合理性没有讨论的余地，最新版的forest也是不支持，通过打印内容排查了大概是忽略了消息体进行发送的。
查了下Get请求通过JSON BODY传参，发现HTTP协议并没有禁止，大体的讨论可以参考：https://zhuanlan.zhihu.com/p/456921996

**Comment by mySingleLive** [comment]
okhttp 会自动忽律 GET 请求的 Body 数据
把 backend 换成 httpclient 就可以了

**Comment by CodingOX** [comment]
> okhttp 会自动忽律 GET 请求的 Body 数据 把 backend 换成 httpclient 就可以了

这个httpclient 看源码指的应该是`org.apache.http.client.HttpClient` 吧？

JDK9之后的`java.net.http.HttpClient`的实现`jdk.internal.net.http.HttpClientImpl`也是一个性能更好的HttpClient...

**Comment by mySingleLive** [comment]
> 

没错，是apache的httpclient

**Comment by CodingOX** [comment]
> > 
> 
> 没错，是apache的httpclient

谢谢！
