### ISSUE TITLE
fastjson2 不支持

### ISSUE THREAD

**Issue by ylq5126** [dromara/forest#107]
JSON converter cannot be found. Please check your classpath if there is the JSON framework, eg. Jackson (>= 2.9.10), Gson or Fastjson (>= 1.2.48), in the dependencies of your project.

maven dependency
<dependency>
            <groupId>com.dtflys.forest</groupId>
            <artifactId>forest-core</artifactId>
            <version>1.5.26</version>
        </dependency>
        
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>2.0.15</version>
        </dependency>
        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>provided</scope>
        </dependency>
        
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.21.7</version>
        </dependency>

**Comment by mySingleLive** [comment]
Currently, Forest does not support fastjson2.
But it will be integrated in future version.
