### ISSUE TITLE
重试配置maxRetryCount不生效

### ISSUE THREAD

**Issue by AlexPfbkdzy** [dromara/forest#111]
版本：
com.dtflys.forest
forest-spring-boot-starter
1.5.16

配置
`@Retry(maxRetryCount = "1", condition = MyRetryCondition.class)`

当业务返回码为异常值时，MyRetryCondition返回true，请求会一直重试
跟踪进代码发现，每次重试记录重试次数的变量都为一个新的对象

`private AtomicInteger currentRetryCount = new AtomicInteger(0);`

**Comment by mySingleLive** [comment]
升级到 1.5.27

**Comment by mySingleLive** [comment]
你的 MyRetryCondition 是如何定义的？

**Comment by AlexPfbkdzy** [comment]
覆盖retryWhen方法，当响应码为 401时返回true，否则返回false
![image](https://user-images.githubusercontent.com/24581931/201575933-ae9d2187-f885-49b1-a0c4-640e25550645.png)

**Comment by AlexPfbkdzy** [comment]
另外，自定义拦截器实现了重试方法，用于token无感刷新，但是获取token失败时会一直重试，设置的最大重试次数无效
![image](https://user-images.githubusercontent.com/24581931/201576368-f1b20755-6a18-4685-9b85-85b5a71f6a0a.png)

**Comment by AlexPfbkdzy** [comment]
感谢作者，我知道怎么回事了，应该过滤token接口的重试

**Comment by mySingleLive** [comment]
好的，不客气
