### ISSUE TITLE
过滤器中请求体系列化后回调函数onBodyEncode不执行

### ISSUE THREAD

**Issue by LiuFqiang** [dromara/forest#113]
Forest: version Backend:okhttp, version 1.5.27
![image](https://user-images.githubusercontent.com/38902658/202646512-e0e69a58-df00-4458-955a-ec5257d1e0fe.png)
![image](https://user-images.githubusercontent.com/38902658/202647341-49667cb5-9ff0-4a19-8b7d-7d64ecf03e98.png)

大佬，我写的测试接口，过滤器中onBodyEncode不执行，直接执行到onSuccess方法里面了
日志信息：
![image](https://user-images.githubusercontent.com/38902658/202647295-f00f7a59-38f6-4125-86d4-72b4a0f23375.png)

**Comment by mySingleLive** [comment]
您好，该功能尚未开放

**Comment by mySingleLive** [comment]
已在`v1.5.28`版本中实现
