### ISSUE TITLE
不同环境如何支持？

### ISSUE THREAD

**Issue by xiechao240** [dromara/forest#117]
@Get("https://jxjy.fjrst.cn/service/regeo?longitude={0}&latitude={1}")
以我现在的场景举例，比如上述一个地址为我与客户项目的对接地址，客户提供给我的测试阶段的地址为
https://jxjytest.fjrst.cn
正式上线时的地址为：
https://jxjy.fjrst.cn
如果不支持变量替换的话，那上线的时候，所有的这种声明都要全部替换，再打包，请问 forest如何支持这种场景？

**Comment by mySingleLive** [comment]
可以将“https://jxjytest.fjrst.cn”域名部分在配置文件设置为全局变量，具体如何使用变量请看文档：

https://forest.dtflyx.com/pages/1.5.x/refer_var/#%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F
