### ISSUE TITLE
multi-thread下會產生雜亂的Url導致失敗

### ISSUE THREAD

**Issue by Zhu-Ying-Zhang** [dromara/forest#136]
1. 在建構Forest時如下所示

```
@Service
@BaseRequest(baseURL="http://www.example.com")
public interface ExampleAPI {
    @Retry(maxRetryCount = "3", maxRetryInterval = "10")
    @GetRequest(url = "/api/v1/test/{id}?startTime=${startTime}&endTime=${endTime}")
    Response<List<TestDto>> getIdList(@Var("id") String id), 
                                      @Var("startTime") Date startTime,
                                      @Var("endTime") Date endTime);
}
```

2. 在使用時

```
LinkedBlockingQueue<String> queue = new LinkedBlockingQueue<>(DBData);
ExecutorService executor = Executors.newFixedThreadPool(4);
CountDownLatch latch = new CountDownLatch(queue.size());

            while (!queue.isEmpty()) {
                String id = queue.poll();

                executor.submit(() -> {
                    try {

                        // Call API
                        Response<List<TestDto>> test = exampleAPI. getIdList(
                            "1"
                            ,  new Date()
                            , new Date()
                        );

                    } catch (Exception ex) {
                       // WARN
                    } finally {
                        latch.countDown();
                    }
                });
            }

            latch.await();

            executor.shutdown();

```

3. Result

```
預期結果：
http://www.example.com/api/v1/test/1?startTime=2023-03-17&endTime=2023-03-17
實際產生：
http://www.http://www.example.com/api/v1/test//api/v1/test/1?startTime=2023-03-17&endTime=2023-03-17
```

看起來會發生這個情況是因為有共享變數導致線程不安全，請問有沒有Configuration可以設定變成線程安全呢？抑或是套件內的共享變數需要修改成被保護的狀態或是使用線程安全的物件來保護高併發的情境底下不會造成Request URL出現亂組合的問題？

**Comment by mySingleLive** [comment]
在 ForestConfiguration 内部使用的集合类型都是类似 ConcurrentHashMap 这种线程安全的并发类型，应该不会出现你这种情况。

而且，每次请求的时候，所对应的 ForestRequest 对象都是独立的，ForestURL 在各个 ForestRequest 对象中也是各自一份，不存在共享的情况。

![image](https://user-images.githubusercontent.com/375398/232026546-98eb65c6-2cc9-48f4-b0dd-a02b19c3ddaa.png)
![image](https://user-images.githubusercontent.com/375398/232026587-e0d9fb2b-1d07-44c3-a7e7-95f0f2c27fac.png)

我在本地机器按照你的代码测试了一遍，没有能重现出你的错误。

为确认问题，想问下你的 Forest 的版本是多少，因为老的版本确实存在线程问题

**Comment by Zhu-Ying-Zhang** [comment]
> 在 ForestConfiguration 内部使用的集合类型都是类似 ConcurrentHashMap 这种线程安全的并发类型，应该不会出现你这种情况。
> 
> 而且，每次请求的时候，所对应的 ForestRequest 对象都是独立的，ForestURL 在各个 ForestRequest 对象中也是各自一份，不存在共享的情况。
> 
> ![image](https://user-images.githubusercontent.com/375398/232026546-98eb65c6-2cc9-48f4-b0dd-a02b19c3ddaa.png) ![image](https://user-images.githubusercontent.com/375398/232028067-9bc833b9-6d72-4776-94a2-592a9f082019.png) ![image](https://user-images.githubusercontent.com/375398/232026587-e0d9fb2b-1d07-44c3-a7e7-95f0f2c27fac.png)
> 
> 我在本地机器按照你的代码测试了一遍，没有能重现出你的错误。
> 
> 为确认问题，想问下你的 Forest 的版本是多少，因为老的版本确实存在线程问题


不好意思，沒有給出更詳細的資訊，我這邊使用的版本是`1.5.10`，想請問要使用什麼版本能夠避免線程不安全的問題呢？

**Comment by mySingleLive** [comment]
1.5.30 就是线程安全的

**Comment by Zhu-Ying-Zhang** [comment]
好的！我先來試試看，太感謝大佬了

**Comment by mySingleLive** [comment]
客气了

**Comment by Zhu-Ying-Zhang** [comment]
升級1.5.30後沒有再出現雜亂的URL，非常感謝 @mySingleLive 大佬的協助

**Comment by mySingleLive** [comment]
不客气
