### ISSUE TITLE
maven中央仓库能找到的1.5.0-RC5

### ISSUE THREAD

**Issue by wzlee** [dromara/forest#141]
最近的版本都怎么不发布啊

**Comment by mySingleLive** [comment]
最新版本已经是 1.5.31 了
因为和过去RC的版本的Maven坐标有些不同，直接按过去的坐标在中央仓库中搜索可能搜索不到
可以到官网 https://forest.dtflyx.com/ 查看最新版本

**Comment by wzlee** [comment]
maven.aliyun.com和search.maven.org用artifactId都搜不到
