### ISSUE TITLE
为啥我用流式接收，没有实时打印，而是最后一下子打印所有

### ISSUE THREAD

**Issue by DonhamSun** [dromara/forest#148]
![image](https://github.com/dromara/forest/assets/53967821/eb3719fe-0b06-4c23-a23d-7c6af1014099)

**Comment by mySingleLive** [comment]
它是不是只有一行内容

**Comment by Stefankeep** [comment]
不是只有一行内容，确实存在问题。
这是通过forest进行调用的代码
```java
     apiClient.exampleSse(vo, (result, req, res) -> {
            // 读过期时间
            try (InputStream inputStream = res.getInputStream(); BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    log.info(line);
                    sendMessage(token, line);
                }
            } catch (Exception e) {
                log.error("读取流错误", e);
            }
        });
```

效果是会一直等待，等接收的流结束之后，才能在这里获取到。

![1696854800770](https://github.com/dromara/forest/assets/15975812/0548a3e8-e4dd-4ea8-9a73-d7f7b91f3131)

可以注意一下请求的实际与实际获取到流的信息的时间差别，有`8秒`。

这是我使用hutool提供的http工具进行调用的代码。

```java
   try (InputStream inputStream = HttpUtil.createPost("https://example.com")
                .body(vo.toString())
                .executeAsync().bodyStream(); BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
            String line;
            while ((line = reader.readLine()) != null) {
                log.info(line);
                sendMessage(token, line);
            }
        } catch (Exception e) {
            log.error("读取流错误", e);
        }
```

![image](https://github.com/dromara/forest/assets/15975812/55c08cf6-f665-4a9d-bf42-f33715ec040a)
可以注意到这里只需要`1秒`,而且相互之间的间隔是存在的，而不是几乎在同一时间。

很喜欢使用这个框架，用来组织规范请求很好，希望能为这个问题的解决提供支持。

**Comment by mySingleLive** [comment]
> 不是只有一行内容，确实存在问题。 这是通过forest进行调用的代码
> 
> ```java
>      apiClient.exampleSse(vo, (result, req, res) -> {
>             // 读过期时间
>             try (InputStream inputStream = res.getInputStream(); BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
>                 String line;
>                 while ((line = reader.readLine()) != null) {
>                     log.info(line);
>                     sendMessage(token, line);
>                 }
>             } catch (Exception e) {
>                 log.error("读取流错误", e);
>             }
>         });
> ```
> 
> 效果是会一直等待，等接收的流结束之后，才能在这里获取到。
> 
> ![1696854800770](https://user-images.githubusercontent.com/15975812/273585598-0548a3e8-e4dd-4ea8-9a73-d7f7b91f3131.jpg)
> 
> 可以注意一下请求的实际与实际获取到流的信息的时间差别，有`8秒`。
> 
> 这是我使用hutool提供的http工具进行调用的代码。
> 
> ```java
>    try (InputStream inputStream = HttpUtil.createPost("https://example.com")
>                 .body(vo.toString())
>                 .executeAsync().bodyStream(); BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
>             String line;
>             while ((line = reader.readLine()) != null) {
>                 log.info(line);
>                 sendMessage(token, line);
>             }
>         } catch (Exception e) {
>             log.error("读取流错误", e);
>         }
> ```
> 
> ![image](https://user-images.githubusercontent.com/15975812/273585328-55c08cf6-f665-4a9d-bf42-f33715ec040a.png) 可以注意到这里只需要`1秒`,而且相互之间的间隔是存在的，而不是几乎在同一时间。
> 
> 很喜欢使用这个框架，用来组织规范请求很好，希望能为这个问题的解决提供支持。

能不能看下 apiClient.exampleSse 的声明方式，有没有添加过 `@DownloadFile` 注解，有的话去掉。
然后尝试以下方式：
1. 如果 forest 不是最新版，升级到最新版  1.5.33
2. apiClient.exampleSse 方法直接返回 InputStream 类型，不用回调函数
3. 关闭请求的 response 日志
4. 后端切换为 httpclient
然后再看看耗时多久

**Comment by Stefankeep** [comment]
感谢你提出的意见。

抱歉没有提供版本号，之前是`1.5.31`，我将版本升级之后，也没能解决问题。

我使用的是 jdk17、springboot3

接着做了如下的尝试：

首先是修改了声明

```java

    @Post(
            url = "/chatglm_pro/sse-invoke"
    )
    ForestResponse<InputStream> aiZpApiChatGlmProSseInvoke1(@Body AiZpApiParamVO body);

    @Post(
            url = "/chatglm_pro/sse-invoke"
    )
    InputStream aiZpApiChatGlmProSseInvoke2(@Body AiZpApiParamVO body);

  @Post(
            url = "/chatglm_pro/sse-invoke",
            async = true
    )
    InputStream aiZpApiChatGlmProSseInvoke(@Body AiZpApiParamVO body);

    @Post(
            url = "/chatglm_pro/sse-invoke",
            async = true
    )
    Future<InputStream> aiZpApiChatGlmProSseInvoke(@Body AiZpApiParamVO body);

    @Post(
            url = "/chatglm_pro/sse-invoke"
    )
    ForestResponse<String> aiZpApiChatGlmProSseInvoke(@Body AiZpApiParamVO body);

```

在调用时，是这样做的

```java

   AiZpApi aiZpApi = SpringUtil.getBean(AiZpApi.class);
        try (InputStream inputStream = aiZpApi.aiZpApiChatGlmProSseInvoke(
                new AiZpApiParamVO()
                        .setPrompt(
                                List.of(
                                        new AiZpApiPromptVO()
                                                .setRole("user")
                                                .setContent("写一个一百字的小童话")
                                )
                        )
        ).getInputStream(); BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))) {
            String line;
            while ((line = reader.readLine()) != null) {
                log.info(line);
            }
        } catch (Exception e) {
            log.error("读取流错误", e);
        }

```

配置均进行了修改，调用与声明相互调整均试了下，比如在 声明 InputStream类型时，更换为 getResult() 来获取流 。

效果仍然是当整个流结束后， 才会 一次性返回。

在之前做AOP日志时，我遇到过这样的一种情况，当在实现中获取了流中的信息，那么返回中就不再具有数据，因此进行copy操作。
所以，日志的问题，我第一时间想到这里，全部关闭，也没有解决问题。

另外，由于我添加了自定义的拦截器用来自动给鉴权，也已经去掉试过了，不是拦截器的问题。

所以有点抓马了。
😂

**Comment by Stefankeep** [comment]
解决了 

这条生效了 **关闭请求的 response 日志** 

一开始 我是使用

```yaml

  log-enabled: false # 打开或关闭日志（默认为 true）
  log-request: true            # 打开/关闭Forest请求日志（默认为 true）
  log-response-status: true               # 打开/关闭Forest响应状态日志（默认为 true）
  log-response-content: false             # 打开/关闭Forest响应内容日志（默认为 false）

```

经过测试发现 


只需要进行一个配置就可以，关闭 ` log-response-status`,关闭这个就可以解决这个问题。其他均不用进行修改

声明采用了

```java

    @Post(
            url = "/chatglm_pro/sse-invoke"
    )
    InputStream aiZpApiChatGlmProSseInvoke(@Body AiZpApiParamVO body);

```

**Comment by Stefankeep** [comment]
通过查看文档，找到了更好的解决方式

在声明时，添加注解即可

```java

    @Post(
            url = "/chatglm_pro/sse-invoke"
    )
    @LogEnabled(
            logResponseStatus = false
    )
    InputStream aiZpApiChatGlmProSseInvoke(@Body AiZpApiParamVO body);

```
