### ISSUE TITLE
ForestResponse<String>里面拿到的getStatusCode() 是-1这个是什么意思

### ISSUE THREAD

**Issue by 617450941** [dromara/forest#153]
ForestResponse<String>里面拿到的getStatusCode() 是-1这个是什么意思

**Comment by mySingleLive** [comment]
-1 指没有拿到确切的 status。一般是服务端接受返回response前，请求过程就发生了错误，比如连接不上，或请求超时等等。这时的 getStatusCode() 就可能是 -1，表示没有得到 response 的 status

**Comment by 617450941** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
