### ISSUE TITLE
MultipartRequestBody 类冲突

### ISSUE THREAD

**Issue by 0x1301FDF** [dromara/forest#154]
find DuplicateClasses
  Found in:
    com.dtflys.forest:forest-core:jar:1.5.33:compile
    com.dtflys.forest:forest-spring:jar:1.5.33:compile
  Duplicate classes:
    com/dtflys/forest/http/body/MultipartRequestBody.class

**Comment by mySingleLive** [comment]
好的，会马上Fix

**Comment by mySingleLive** [comment]
https://github.com/dromara/forest/issues/154
