### ISSUE TITLE
使用post请求文件流下载，使用byte[]接收，异常

### ISSUE THREAD

**Issue by gclm** [dromara/forest#155]
## 代码
![image](https://github.com/dromara/forest/assets/27618687/a62f4b71-7b26-45c3-9394-db17f2d22221)

## 错误

![1F273FE8-B48C-44a8-954A-57029DC39056](https://github.com/dromara/forest/assets/27618687/66855cff-2f73-4237-87d9-c860a43acb6f)

**Comment by mySingleLive** [comment]
这种错误一般是因为客户端还没读取完，服务端就把连接关闭了，你可以尝试用流的方式来做

```java
ForestResponse getTTSByte(@JSONBody AliTTSConfig config);

...


ForestResponse res = getTTSBytes(...);
if (res.isSuccess()) {
  try (InputStream in = res.getInputStream()) {
    String content = IOUtils.toString(in, StandardCharsets.UTF_8);
  }
}
```

**Comment by gclm** [comment]
好的，感谢
