### ISSUE TITLE
get请求 参数中有中文被转译

### ISSUE THREAD

**Issue by liuluobing321** [dromara/forest#156]
在调用第三方api中，get请求某一参数内容为中文，使用forest进行调用，中文被转译，目标服务器不能识别，导致查询数据失败。
被转译url：
https://api.map.baidu.com/place/v2/search?query=%E9%93%B6%E8%A1%8C&location=39.915,116.404&radius=2000&output=json
正确url应为：
https://api.map.baidu.com/place/v2/search?query=银行&location=39.915,116.404&radius=2000&output=json

请问如何解决，谢谢

**Comment by mySingleLive** [comment]
按照 HTTP 的标准，中文是无法直接通过URL参数传输的，必须要经过 URLEncode，也就是你上面贴出来的转译后的样子
