### ISSUE TITLE
使用httpclient作为实现时，是否可配置httpclient原生的HttpRequestInterceptor

### ISSUE THREAD

**Issue by qiangbro** [dromara/forest#16]
如题，希望可支持配置httpclient原生的HttpRequestInterceptor

**Comment by shollin** [comment]
https请求时，如果keystore是动态变化的，如何处理？如下代码
`interface PayClient{
		
		@Post(url = "https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers"
				,sslProtocol = "SSL"
				,keyStore="${keyStore}"
				,contentType = "application/xml")
	    String transfers(@Body(filter = "xml") Transfers transfers,@DataVariable("keyStore") String keyStore);
		
		
	}`

**Comment by mySingleLive** [comment]
> https请求时，如果keystore是动态变化的，如何处理？如下代码
> 
> ```
> interface PayClient{
> 		
> 		@Post(url = "https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers"
> 				,sslProtocol = "SSL"
> 				,keyStore="${keyStore}"
> 				,contentType = "application/xml")
> 	    String transfers(@Body(filter = "xml") Transfers transfers,@DataVariable("keyStore") String keyStore);
> 		
> 		
> 	}```
> ```

这个问题已经解决，issue：https://gitee.com/dt_flys/forest/issues/I1WXB5
