### ISSUE TITLE
forest适配Spring Cloud  gitee-I7U45G,gitee-I63VG0,gitee-I4K8IS

### ISSUE THREAD

**Issue by galaxy-sea** [dromara/forest#164]
[gitee-I7U45G](https://gitee.com/dromara/forest/issues/I7U45G), [gitee-I63VG0](https://gitee.com/dromara/forest/issues/I63VG0), [gitee-I4K8IS](https://gitee.com/dromara/forest/issues/I4K8IS)

> demo：
```java
public interface HelloClient {

    @Get("http://localhost:8080/hello/hello")
    @LoadBalancer("example-springcloud")
    Map<String, String> hello();
}
```

大致的想法是提供一个`@LoadBalancer`来实现微服务的负载均衡

**Comment by galaxy-sea** [comment]
我提交了一个[PR-165](https://github.com/dromara/forest/pull/165)来适配Spring Cloud

**Comment by yl-yue** [comment]
> 我提交了一个[PR-165](https://github.com/dromara/forest/pull/165)来适配Spring Cloud

被拒绝了。。

**Comment by galaxy-sea** [comment]
> > 我提交了一个[PR-165](https://github.com/dromara/forest/pull/165)来适配Spring Cloud
> 
> 被拒绝了。。

很抱歉, 不能解决你的问题, 如果需要你可以复制相关代码到自己工程之中即可
