### ISSUE TITLE
The singleton of httpclient

### ISSUE THREAD

**Issue by dawn2zhang** [dromara/forest#21]
I think the httpclient/okhttpclient should singleton in connectionManager. Now the per request has a client. It’s so heavy and the most import is that the connection pool of client doesn‘t work.

**Comment by zlm0125** [comment]
The okhttpclient should init only one client instance and use newBuilder() to make method-level configuration effective and be able to reuse connection pools.
The same, httpclient should init only one client instance and use requestConfig.
In current situation the memory is burst.
I try to submit pr, but unfortunately I find the code needs to be refactored urgently. Sorry for my unsubmitted.

**Comment by mySingleLive** [comment]
Thanks for your advice. 

I'll use a cache to store clients. The different requests from a same method will have only one client.
