### ISSUE TITLE
retry-count 配置后,重制机制不生效

### ISSUE THREAD

**Issue by pyygithub** [dromara/forest#22]

**Comment by pyygithub** [comment]
forest:
   retry-count: 2 # 请求失败后重试次数，默认为0次不重试

application.yml 配置无效

在方法中配置 retry-count 有效

**Comment by mySingleLive** [comment]
是什么版本？

**Comment by mySingleLive** [comment]
新版本应该不会再有该问题，可以升级到最新版`1.5.21`
