### ISSUE TITLE
springboot整合时，MultipartFile接收图片文件时contentType值不对

### ISSUE THREAD

**Issue by ShiTianming** [dromara/forest#27]
文档([上传下载](http://dt_flys.gitee.io/forest-website/docs/adv/upload_download))给出：
```
@PostRequest(url = "/upload")
Map upload(@DataFile(value = "file") MultipartFile multipartFile, OnProgress onProgress);
```
上传文件为图片时multipartFile的`contentType= image/jpeg`，upload给另外一个接口时，另外接口接收到的multipartFile的`contentType= multipart/form-data`。

**Comment by mySingleLive** [comment]
好的，我看一下

**Comment by mySingleLive** [comment]
新版本1.5.2-BETA解决了该问题
