### ISSUE TITLE
文件下载时OnProgress没有执行

### ISSUE THREAD

**Issue by ngchunhoCR7** [dromara/forest#29]
![image](https://user-images.githubusercontent.com/41767241/112418551-a803cf00-8d64-11eb-9897-999ec65c2b05.png)
OnProgress的日志没有打印

**Comment by mySingleLive** [comment]
OnProgress的断点进来了吗？

**Comment by ngchunhoCR7** [comment]
断点也没有进去，但是文件是成功下载了


 

-------- 原始邮件 --------
发件人：公子骏 ***@***.***>
时间：2021年3月29日 16:14
收件人：dromara/forest ***@***.***>
抄送：ngchunho ***@***.***>,Author ***@***.***>
主题：Re: [dromara/forest] 文件下载时OnProgress没有执行 (#29)

**Comment by mySingleLive** [comment]
请问是什么版本的Forest？

**Comment by ngchunhoCR7** [comment]
1.5.0-RC7的


 

-------- 原始邮件 --------
发件人：公子骏 ***@***.***>
时间：2021年3月30日 13:48
收件人：dromara/forest ***@***.***>
抄送：ngchunho ***@***.***>,Author ***@***.***>
主题：Re: [dromara/forest] 文件下载时OnProgress没有执行 (#29)

**Comment by mySingleLive** [comment]
是不是下载的文件比较小？没还来得及进入onProgress就已经下载好了

**Comment by mySingleLive** [comment]
建议换成正式版 1.5.0

**Comment by ngchunhoCR7** [comment]
好的 我测试的是一张几百k的图片 已换成1.5.0的正式版使用了


 

-------- 原始邮件 --------
发件人：公子骏 ***@***.***>
时间：2021年4月1日 11:46
收件人：dromara/forest ***@***.***>
抄送：ngchunho ***@***.***>,Author ***@***.***>
主题：Re: [dromara/forest] 文件下载时OnProgress没有执行 (#29)

**Comment by mySingleLive** [comment]
几百k的图片可能来不及onProgress就已经完成了，换几十M的文件试试呢

**Comment by mySingleLive** [comment]
不好意思，平时在gitee待的时间比较多，github的issue偶尔容易疏忽，方便的话可以移步到gitee：https://gitee.com/dromara/forest 讨论这个问题
