### ISSUE TITLE
forest-spring-boot-starter version:1.5.0 url param not encode.

### ISSUE THREAD

**Issue by usami-muzugi** [dromara/forest#32]
使用forest-spring-boot-starter执行HTTP请求时，默认backend为okhttp3。
debug发现并未对Query参数进行URL Encode，
调用链路
com.dtflys.forest.backend.okhttp3.executor.AbstractOkHttp3Executor#execute(com.dtflys.forest.handler.LifeCycleHandler, int)
com.dtflys.forest.backend.url.SimpleURLBuilder#buildUrl

backend修改为httpclient调用的com.dtflys.forest.backend.url.QueryableURLBuilder则进行了正常URL Encode。
![image](https://user-images.githubusercontent.com/17221756/114593279-7eccc380-9cbe-11eb-891f-6fc276340351.png)
![image](https://user-images.githubusercontent.com/17221756/114593304-87bd9500-9cbe-11eb-8e97-dc916d6cf9e5.png)

请修复

**Comment by mySingleLive** [comment]
好的，我看下

**Comment by nnzbz** [comment]
现在1.5.2-BETA仍存在此问题，底层的OkHttp框架并没有对URL中的参数进行URLEncoding编码

**Comment by mySingleLive** [comment]
@nnzbz okhttp不会对URL进行编码，在1.5.2-BETA可以用 `{url}` 的新字符串模板对变量进行强制URLEncoding编码

**Comment by mySingleLive** [comment]
已在 `1.5.21` 及以上版本解决，现在不同url部分有不同的URLEncode强度级别，都会按符合HTTP标准的最低强度去编码，如果最低强度不能满足要求，可以在字符串模板中调用 encode(xxx) 进行最大强度编码来解决

```java
@Get("/test?name={encode(name)}")
String test(@Var("name") String name);
```
