### ISSUE TITLE
ForestJacksonConverter 可否支持一下自定义配置

### ISSUE THREAD

**Issue by imhuzi** [dromara/forest#34]
ForestJacksonConverter 可否支持一下自定义配置，比如 下划线 转驼峰支持 一些 api 接口 返回数据是 下划线格式的字段，需要自动映射为 驼峰格式，需要 
```java
 mapper.setPropertyNamingStrategy(PropertyNamingStrategy.SNAKE_CASE);
```

**Comment by leesonwei** [comment]
可以通過
`/**
     * 获取Jackson的Mapper对象
     * @return Jackson的Mapper对象，{@link ObjectMapper}类实例
     */
    public ObjectMapper getMapper() {
        return mapper;
    }`
方法獲取mapper對象然後進行修改.
