### ISSUE TITLE
自定义注解优化建议

### ISSUE THREAD

**Issue by chinagoldline** [dromara/forest#37]
当使用自定义注解时，注解变量的值引用Forest全局变量进行赋值，当全局变量定义不存在时，
会报空指针异常。此处建议优化为，当全局变量的引用值为空时，使用自定义注解的对应字段的默认值，
没有默认值时再抛异常。
举例如下：

public  @interface ForestPorxy {
    String isProxy() default "false";
}
@GetRequest(url = "https:.//www.baidu.com")
@ForestPorxy(isProxy = "${proxy.baidui}")
ForestResponse<String>  evtBaidu();

如果proxy.baidui 在配置文件中不存在，现在的版本为直接抛出异常，且不会进入自定义注解的生命周期。

**Comment by mySingleLive** [comment]
感谢您的建议，关于占位符中的变量默认值的做法我们会考虑处理的，预计会在1.6.0之后版本进行支持

**Comment by othorizon** [comment]
> 感谢您的建议，关于占位符中的变量默认值的做法我们会考虑处理的，预计会在1.6.0之后版本进行支持

现在由于业务场景需要，亟需默认值这个功能（为了实现开发零配置，但又可以特殊场景下去配置变量值），现在正在研究怎么临时想办法支持默认值，还没想出好办法。。。

**Comment by othorizon** [comment]
> > 感谢您的建议，关于占位符中的变量默认值的做法我们会考虑处理的，预计会在1.6.0之后版本进行支持
> 
> 现在由于业务场景需要，亟需默认值这个功能（为了实现开发零配置，但又可以特殊场景下去配置变量值），现在正在研究怎么临时想办法支持默认值，还没想出好办法。。。

解决了哈哈，通过类加载优先级顺序的机制，覆盖了源码中的com.dtflys.forest.mapping.MappingReference 这个类，然后自己重新实现了默认值的逻辑。

**Comment by mySingleLive** [comment]
> > > 感谢您的建议，关于占位符中的变量默认值的做法我们会考虑处理的，预计会在1.6.0之后版本进行支持
> > 
> > 
> > 现在由于业务场景需要，亟需默认值这个功能（为了实现开发零配置，但又可以特殊场景下去配置变量值），现在正在研究怎么临时想办法支持默认值，还没想出好办法。。。
> 
> 解决了哈哈，通过类加载优先级顺序的机制，覆盖了源码中的com.dtflys.forest.mapping.MappingReference 这个类，然后自己重新实现了默认值的逻辑。

厉害，我都没想到这步
