### ISSUE TITLE
这框架支持在Android项目内使用吗？

### ISSUE THREAD

**Issue by spysoos** [dromara/forest#39]
这框架支持在Android项目内使用吗？需要什么特别的配置吗？

**Comment by mySingleLive** [comment]
改框架基于okhttp和httpclient，理论上okhttp在android上能用，forest就能用。
但目前我并没有在android上尝试过，没有去做专门对android的支持。

**Comment by PuppiesMeat** [comment]
有在android上支持的打算吗？我试了下，配置文件好像有问题

**Comment by mySingleLive** [comment]
是想支持，如果有更多贡献者参与的话 ~
