### ISSUE TITLE
不支持读取父接口的注解

### ISSUE THREAD

**Issue by iszhangsc** [dromara/forest#40]
forest-spring-boot-starter 1.5.0 版本， 接口调用上不能读取父接口上的注解信息. 比如@BaseRequest 注解

**Comment by mySingleLive** [comment]
暂时不支持@BaseRequest注解的父类继承机制

**Comment by iszhangsc** [comment]
好的

**Comment by mySingleLive** [comment]
已在 1.5.8 版本中支持注解继承机制
