### ISSUE TITLE
关于retryer的使用，能不能在文档里面介绍一下呢？

### ISSUE THREAD

**Issue by chenjinlin616** [dromara/forest#44]
看源代码里有NoneRetryer和BackOffRetryer；不是很清晰他的作用，或者能否自定义Retryer

**Comment by mySingleLive** [comment]
Retryer是作用是指定重试的策略，即按某种等待时间去重试。如：BackOffRetryer是以二进制退避算法形式让每次超时后等待重试的时间进行递增。
但Retryer的策略不包括重试条件，即不能修改触发重试的条件逻辑。

**Comment by mySingleLive** [comment]
https://forest.dtflyx.com/docs/basic/retry
