### ISSUE TITLE
SSL模块是否可以开放接口支持外部配置？

### ISSUE THREAD

**Issue by start621** [dromara/forest#55]
1. keyStore口令仅支持明文配置
2. 证书校验的TrustStrategy目前不支持自定义，仅有TrustSelfSignedStrategy()或new TrustAllManager()
3. ForestSSLConnectionFactory中hostnameVerifier不支持外部定义

**Comment by mySingleLive** [comment]
新版本 1.5.2-BETA3 中，可以自定义构造 SSLSocketFactory 对象。
可以参考此issue： https://gitee.com/dromara/forest/issues/I3VRAB
