### ISSUE TITLE
baseURL 不生效，会默认加上localhost

### ISSUE THREAD

**Issue by Narcasserun** [dromara/forest#61]
![image](https://user-images.githubusercontent.com/39329477/143404514-d6068e80-29f7-4187-a859-314da54489eb.png)
![image](https://user-images.githubusercontent.com/39329477/143404549-6c3eecbf-af1f-47fd-85e7-f194d967c78e.png)
![image](https://user-images.githubusercontent.com/39329477/143404631-149c3980-120b-4271-b939-23c2d82cc1d5.png)

**Comment by mySingleLive** [comment]
请问是什么版本，前几个版本是有这个问题

**Comment by mySingleLive** [comment]
已在新版本fix，可升级到`1.5.21`
