### ISSUE TITLE
BUG: java.lang.IllegalArgumentException:Socket may not be null

### ISSUE THREAD

**Issue by mlmdflr** [dromara/forest#73]
forest version: 1.5.19
springboot version: v2.4.4
backend: httpclient v4.5.13

throw error setup HTTPProxy  

![image](https://user-images.githubusercontent.com/93173537/155270658-f69b5805-5e90-43c8-a729-1ee4dd0b2ff8.png)

**Comment by mySingleLive** [comment]
希望提供下能重现这个问题的 CASE，包括：
1. 出问题的接口定义
2. 出问题的调用方式和参数数据

**Comment by mlmdflr** [comment]
![image](https://user-images.githubusercontent.com/93173537/155437010-f5888e41-4a0f-4383-a9b3-7d54be9a22c2.png)

![image](https://user-images.githubusercontent.com/93173537/155437039-0db12dd0-2a68-49a3-9cd5-25182b5a127e.png)

**Comment by benname** [comment]
同碰到了，同设置了代理

**Comment by mlmdflr** [comment]
@mySingleLive 1.5.20 solve?

**Comment by tanglinyan** [comment]
@HTTPProxy注解在https请求上会导致该问题的产生，#fix-73进行解决

**Comment by mlmdflr** [comment]
v1.5.23 fix
