### ISSUE TITLE
timeout配置方法是废弃的,那么使用什么方法呢,没有link吗

### ISSUE THREAD

**Issue by filusilia** [dromara/forest#89]
/**
     * 设置全局的请求超时时间，单位为毫秒
     *
     * @param timeout 请求超时时间，单位为毫秒
     * @return 当前ForestConfiguration实例
     */
    @Deprecated
configuration.setTimeout(3000);

已经废弃的使用,是没有新方法还是直接不建议timeout了

**Comment by mySingleLive** [comment]
现在 timeout 被更细化的 connect-timeout 和 read-timeout 属性所替代
