### ISSUE TITLE
@Body注解对象，请求体漏变量

### ISSUE THREAD

**Issue by boasad** [dromara/forest#94]
@Body注解对象时，当类中有部分的成员变量值未赋值时(也就是默认值)，请求体中并不会带上这一部分值.
具体看:
![image](https://user-images.githubusercontent.com/64964182/174813272-2f931269-aede-4de0-b6c4-d8618aa45ef4.png)
 这一些字段名是预留的，所以并没有赋值，保留的是java默认为成员变量的值
在请求过程中,Body中并不会携带这一部分:
![image](https://user-images.githubusercontent.com/64964182/174812296-c0effff6-4c1f-4f56-b972-24177f8cbbe8.png)
但有些 情况下又需要这些预留值，希望能改进这一部分!
期望预期:
![image](https://user-images.githubusercontent.com/64964182/174812925-150ba45a-cbf4-43fe-88cf-cc24b6763388.png)

**Comment by mySingleLive** [comment]
目前没法自动做到这一点
可以将这些保留字段设置为空字符串，如：activityTrack = "";
