### ISSUE TITLE
请求的@Body字段中的值有特殊符号被漏掉

### ISSUE THREAD

**Issue by misswolf** [dromara/forest#97]
接口中定义：
@Post(url="authenticate", contentType = "application/x-www-form-urlencoded")
    Result authenticate(@Body("username") String username, @Body("password") String password);

调用：
       String username = "zhangsan";
        String password = "123465+654321";
        Result resp = portalAuthenticateClient.authenticate( username,password)
在服务器上收到的password时+变成了空格
困扰了很久，在线上排查了很久，通过wireshark才发现问题所在

**Comment by mySingleLive** [comment]
需要先 URL Encode 再传入

**Comment by misswolf** [comment]
加了urlencode的确是可以

**Comment by Qjjie** [comment]
只能自己手动设置UrlEncode吗，forest有没有地方设置？

**Comment by Qjjie** [comment]
@BodyType(type = "json", encoder = ForestJacksonConverter.class)
@Post(url = "/", contentType = ContentType.APPLICATION_X_WWW_FORM_URLENCODED)
String send(@Body Entry entry);
这样不行，但是提前URLEncoder.encode(json, "UTF-8");就可以的
